### ISSUE TITLE
Crashes after a few seconds of any 3-D?

### ISSUE THREAD

**Issue by cxd4** [purplemarshmallow/z64#12]
Quest 64, Mario, Virtual Chess, Bomberman, Zelda, Banjo-Kazooie ...
Seems any game with 3-D in it will suddenly terminate z64gl (but not z64) after a few seconds.

Virtual Chess 64 doesn't crash if I press through the 3-D in the intro and switch from the 3-D to the 2-D chessboard, then I can play forever without any crashing, I think.

Could this be a 64-bit issue or an issue just with the Linux build, or even a driver issue on my end?

Can somebody use Visual Studio to do a 64-bit build of this plugin?  I know we have a working 64-bit interpreter-only Windows emulator, Project64, that people should be able to plug z64gl into.

Otherwise when I wake up tomorrow I will start to look at debugging this.

**Comment by purplemarshmallow** [comment]
I made a 64 bit build with Visual Studio and tested on PJ64. It's fully working I can't notice any problems

**Comment by cxd4** [comment]
kk update:
The very first two commits of this repository do not have this crashing.

So z64gl r12 works:  https://github.com/purplemarshmallow/z64/tree/63791e386b86fd460db1d356b5c179b8c7d35f3a

And z64gl r15 works:  https://github.com/purplemarshmallow/z64/tree/afec16242e2f897450a6204a5f0ada86462ebfe7

But doing a `git checkout` to the commit immediately after that, in which you upgraded to z64gl r17, somehow this guaranteed crashing after a few seconds of any 3-D triangles being rendered begins to happen.  Something about ziggy's changes after r15 of his plugin must be connected to this issue somehow.

**Comment by cxd4** [comment]
No combination of settings in `z64gl.conf` seems to fix it, but I can note that combining `threaded=1` with `async=1` (which requires the former anyway) instantly causes an assertion upon starting emulation in this emulator fork I'm using.  No big deal as those default to =0 anyway.

**Comment by purplemarshmallow** [comment]
> I can note that combining threaded=1 with async=1 (which requires the former anyway) instantly causes an assertion upon starting emulation in this emulator fork I'm using

This causes instabilities with any version of this plugin only a few games work with it. I'm not sure if it's worth to keep the async setting. On the other hand World Driver Championship is much faster with async, it makes a big difference.

**Comment by LegendOfDragoon** [comment]
> On the other hand World Driver Championship is much faster with async, it makes a big difference.

That's odd because async hardly made a difference for me in that game. I guess it's because z64gl is faster for you in the first place. I gotta see if I get better performance in linux with z64gl.

> I'm not sure if it's worth to keep the async setting

I'd keep it. It helps me get closer to full speed in Super Smash Bros.

**Comment by cxd4** [comment]
Looks like the crash is coming from somewhere in the LOADBLOCK command.

But.

The crash is in actuality, fixed by replacing only rdp_process_list() with the version of the function from z64 r15 instead of r17, as LOADBLOCK was completely unchanged by the commit to upgrade to r17.

``` c
printf("h:  cmd = %u, rdp_cmd_cur = %u, rdp_cmd_data = %p, rdp_cmd_ptr = %u\n", cmd, rdp_cmd_cur, rdp_cmd_data);
        // execute the command
        rdp_command_table[cmd](rdp_cmd_data[rdp_cmd_cur+0], rdp_cmd_data[rdp_cmd_cur+1]);
puts("i");
```

output:

```
h:  cmd = 51, rdp_cmd_cur = 446, rdp_cmd_data = 0x7f6b1fbffb60, rdp_cmd_ptr = 448
LOADBLOCK start
Signal number 11 caught:
        errno = 0 (Success)
```

So it makes it up to the puts("h"); but crashes before the puts("i");.

The game usually completes the whole LOADBLOCK command successfully a few times prior before the call to it that finally does crash on my system.

**Comment by purplemarshmallow** [comment]
What happens if you use this branch? https://github.com/purplemarshmallow/z64/tree/angrylion-integration
it uses the loadblock command from angrylion's plugin

**Comment by cxd4** [comment]
EDIT:  trying the above post now

Got it more specifically.  It's crashing here:
https://github.com/purplemarshmallow/z64/blob/master/src/rdp.cpp#L452-L453

So with debugging that:

```
puts("a");
  MarkTmemArea(rdpTiles[tilenum].tmem, rdpTiles[tilenum].tmem + width,
               tl * rdpTiWidth*4 + rdpTiAddress + sl*4, 0, ~0, ~0);
puts("b");
```

It writes "a" to the console, but the crash is always before "b".

Like I said, LOADBLOCK is successfully executed plenty of times before the LOADBLOCK call that finally crashes on this line of code finally is executed.  For Mario64 it crashes in load_block after 2000 something successful LOADBLOCK calls; for Virtual Chess 64 it's always 5240 successful calls.  Still always crashes at that line.

**Comment by purplemarshmallow** [comment]
MarkTmemArea tells the plugin where the data in TMEM came from. This is needed for this plugin's framebuffer emulation. Unfortunately there are many TMEM issues and I'm not sure if MarkTmemArea is always correct. If it can be improved maybe framebuffer emulation will also work better

**Comment by cxd4** [comment]
I'm unable to get your `angrylion-integration` branch to work.  I had a few run-time dynamic link errors to fix from your changes, but ultimately it seems that the new `rdp-software` module is dependent on things from `<windows.h>`.

For the moment, I will find it faster to just look at debugging where inside MarkTmemArea it crashes.

**Comment by cxd4** [comment]
Found the next hint.  Observe console output:

```
nbTmemAreas = 0
nbTmemAreas = 0
nbTmemAreas = 0
nbTmemAreas = 0
nbTmemAreas = 0
nbTmemAreas = 0
nbTmemAreas = 0
nbTmemAreas = 0
(... thousands more to follow ...)
nbTmemAreas = 0
nbTmemAreas = -676165696
Signal number 11 caught:
        errno = 0 (Success)
```

That last value of `nbTmemAreas` is pretty understandable for causing a segfault at:
https://github.com/purplemarshmallow/z64/blob/master/src/rdp.cpp#L90-L95

**Comment by cxd4** [comment]
Further debugging proves that the value of nbTmemAreas is being corrupted by this:

``` c
if (rdp_cmd_cur + rdp_command_length[cmd]/4 > MAXCMD)
    memcpy(rdp_cmd_data + MAXCMD, rdp_cmd_data, rdp_command_length[cmd] - (MAXCMD - rdp_cmd_cur)*4);
```

This memcpy() is severely leaking, to the point where it actually overwrites a global variable such as `nbTmemAreas`.  This could be debugged via:

``` c

    if (rdp_cmd_cur + rdp_command_length[cmd]/4 > MAXCMD) {
printf("before:  nbTmemAreas = %i\n", nbTmemAreas);
        memcpy(
            rdp_cmd_data + MAXCMD,
            rdp_cmd_data,
            rdp_command_length[cmd] - 4*(MAXCMD - rdp_cmd_cur)
        );
printf("after :  nbTmemAreas = %i\n", nbTmemAreas);
    }
```

results, since boot:

```
before:  nbTmemAreas = 1
after :  nbTmemAreas = 1
before:  nbTmemAreas = 1
after :  nbTmemAreas = 1
before:  nbTmemAreas = 1
after :  nbTmemAreas = -676165696
Signal number 11 caught:
        errno = 0 (Success)
```

**Comment by purplemarshmallow** [comment]
Nice find
Gonetz copied this bug to GLideN64 and I copied it to PJ64Glide...

**Comment by cxd4** [comment]
I've just proposed a PR to "fix" this bug.

It fixes all memory leaks, but at the expense of dropping a few drawing commands that could not fit into memory (rather than writing them in and causing the memory leak).  A real, genuine fix to this issue may be applied later to remove the MAXCMD limit altogether.

**Comment by AmbientMalice** [comment]
> Nice find
> Gonetz copied this bug to GLideN64 and I copied it to PJ64Glide...

Do you think it's causing any issues over there? I notice that z64gl no longer seems to have texture freak outs at random in Factor 5 games. I assume this change might be related.

**Comment by cxd4** [comment]
Yes, I believe I may have fixed the texture crashes on accident with this change.
I did always have those texture corruptions on Windows playing _Super Smash Bros._ and such.

With global memory corruption like this, the variety of potential bugs accidentally fixed can be endless.

Tempted to close the issue but probably ought to keep it open to remind me to do a full fix.

**Comment by purplemarshmallow** [comment]
@cxd4 I can confirm you fixed these texture corruption problems. The plugin now also works if I build with linker optimizations.

**Comment by purplemarshmallow** [comment]
I guess getting rid of MAXCMD would be the best solution but if CMD_OVERFLOW_RESERVE is big enough I think it's also very safe

**Comment by cxd4** [comment]
Yeah removing it would be best.  This is that one thing in angrylion's latest commits that I jumped over implementing, due to no games needing it generally and no pragmatic need to rearrange the structure of things just for that.  I think that due to this issue, I ought to merge his solution into my fork of angrylion's plugin, and then I'll decide on a method of my choosing for dealing with the version here.

Though for the present time being, aside from `printf`ing to the console every few seconds, well I don't think I am seeing any graphically based issues now.

**Comment by purplemarshmallow** [comment]
I looked again at the implementation in Glide64/GLideN64. They cut off all data above 0x100000. The same memcpy is there but it never gets executed.

**Comment by AmbientMalice** [comment]
> I looked again at the implementation in Glide64/GLideN64. They cut off all data above 0x100000. The same memcpy is there but it never gets executed.

Since GLideN64 lacks the odd visual tearing, depth corruption, and distortion of pre-fix z64gl, I assumed it must have been behaving differently somehow. I assume that cutting off data means it can't overflow and corrupt memory, but what is cutting off doing compared to using an overflow buffer? Or is it basically the same thing, but cruder?

**Comment by purplemarshmallow** [comment]
I'm not sure if GLideN64's and z64gl's implementations give the same results but both are incorrect

**Comment by cxd4** [comment]
I think it's been long enough that I can close this.

I don't really feel like looking into making the DP command buffer recursive or making it dispatch to a temporary queue, refill it and load up extra memory unless we find a game that actually takes advantage of huge DPC list sizes.

Beat Zelda and been playing _Quest 64_ here on Linux with this plugin just fine for the past month.
