### ISSUE TITLE
depth compare issues

### ISSUE THREAD

**Issue by purplemarshmallow** [purplemarshmallow/z64#19]
https://github.com/purplemarshmallow/z64/blob/master/src/rgl_rendermode.cpp#L27
N64 depth compare modes can be approximated with OpenGL depth compare. In this article it's described very well http://gliden64.blogspot.co.at/2014/07/depth-buffer-emulation.html
GLideN64 does not have as many depth compare issues I think that's a good reference here.

I can confirm these issues in z64gl come from incorrect depth compare emulation (and other plugins with hardware rendering work correctly):
- Super Mario 64 missing hand at title screen
- Winback missing HUD
- Duke Nukem 64 missing menus and HUD
- Superman incorrect background assembling effect during intro
- Hexen missing weapons(?)

**Comment by ghost** [comment]
Good thing to do would be doing 16 bit depth via depth textures. GL 4.5 seems a bit too much. GL3.3 seems to be a decent baseline.

**Comment by purplemarshmallow** [comment]
The problems mentioned above are fixed now so I'm closing
