### ISSUE TITLE
Kirby 64 crashes ingame

### ISSUE THREAD

**Issue by purplemarshmallow** [purplemarshmallow/z64#21]
It crashes with the official r17 version and also with the current master
Savestate: [Kirby 64 - The Crystal Shards (E).pj.zip](https://github.com/purplemarshmallow/z64/files/177124/Kirby.64.-.The.Crystal.Shards.E.pj.zip)

No crash with the angrylion integration branch. So the problem is either in the load_tile, load_tlut or load_block commands or in rdp_process_list (because I replaced these parts in this branch)

**Comment by cxd4** [comment]
Hm, I don't have that game but it's probably `rdp_process_list()`.

If not, I imagine deleting the code contents of the other 3 functions you mentioned (leaving them down to null, empty functions) would suddenly cure the crash (obv. have missing/wrong graphics though).

**Comment by purplemarshmallow** [comment]
load_tlut crashes right here
https://github.com/purplemarshmallow/z64/blob/master/src/rdp.cpp#L407
Same problem in Glover it crashes here after the intro

https://github.com/mamedev/mame/blob/master/src/mame/video/n64.cpp#L2487
I think that's a good reference but I have not managed to fix it yet.

**Comment by purplemarshmallow** [comment]
MAME's code can't be 1:1 copy-pasted, other parts work differntly
MAME has this `if (dststart < 2048)` limit I think that needs to be implemented correctly to fix the crash

**Comment by cxd4** [comment]
I guess it depends whether it's the memory access to dst[], or to src[] that is crashing by that line.

It's more likely to be dst[] I think, as the TMEM base pointer is the more local issue to the plugin.

On the other hand, if it's the src[i ^ 1] that is crashing, either one of the sources to computing the `uint16_t* src = ...` is corrupted, or maybe it's just unmapped memory due to using 4 MB, and maybe using 8 MB RDRAM in the pj64 RDB would affect that issue.

**Comment by purplemarshmallow** [comment]
Access to src[] causes the crash
To avoid crashes with dst[] the plugin uses 4*0x1000 as TMEM size instead of 0x1000 which is not ideal
8MB RDRAM does not help

**Comment by purplemarshmallow** [comment]
but using 16MB RDRAM fixes the crash
Maybe it just needs a check to stay inside RDRAM?

**Comment by cxd4** [comment]
That is interesting.  So I would probably in my head at least start out changing this:

``` c
uint16_t *src = (uint16_t *)&rdram[(rdpTiAddress + (tile.tl >>2) * rdpTiWidth * 2 + ((tile.sl >>2) << rdpTiSize >> 1))/4];
```

... to this ...

``` c
size_t address = rdpTiAddress + (tile.tl >>2) * rdpTiWidth * 2 + ((tile.sl >>2) << rdpTiSize >> 1);
uint16_t *src = (uint16_t *)&rdram[address / 4];
```

The [address / 4] I believe is because ziggy's `rdram` #define really being a macro for aliasing the uint8_t RDRAM bytes array to a pointer to uint32_t's ... which warrants dividing by /= 4.

Therefore I think the comparison of interest here is:

``` c
if (address > 0x003FFFFF) /* for 4 MB RDRAM limit...change as needed for 8, 16 etc. */
    (Abort the function with an early exit to avoid the crash.)
```

Or, instead of early exiting, follow angrylion's reverse-engineering of the RDP and read out 0 bytes (as in, `dst[4*i] = 0x00;`) from un-mapped RDRAM addresses that are out of bounds.

Or, the whole computation behind my new `size_t address` variable is still bound by something buggy with ziggy's determination of the offset.

**Comment by cxd4** [comment]
https://github.com/mamedev/mame/blob/master/src/mame/video/n64.cpp#L2521

As I recall, the macro being used here at the end of this line is designed to check for out-of-range addresses that could cause a crash.  If you ever find a way to test this MAME version of the command directly into z64gl, replacing that macro function with a direct reference to aliasing the TMEM read without checking to see if it crashes then would be one way to tell why this version of the RDP is immunized from this.

**Comment by purplemarshmallow** [comment]
> `if (address > 0x003FFFFF) /* for 4 MB RDRAM limit...change as needed for 8, 16 etc. */
>     (Abort the function with an early exit to avoid the crash.)`

This fixes the crash. How can I detect the RDRAM size? Is there a not platform specific way to do this?

> The [address / 4] I believe is because ziggy's rdram #define really being a macro for aliasing the uint8_t RDRAM bytes array to a pointer to uint32_t's ... which warrants dividing by /= 4.

I think introducing new RDRAM macros would be better than dividing by 4

**Comment by cxd4** [comment]
There are platform-specific ways to do it, but there is no portable way to do it.

I always did tell zilmar that the PLUGIN_INFO structs should have had a member telling us a `size_t` variable containing the number of bytes or MiB allocated to the plugin_info.RDRAM pointer.  The closest thing to a cross-platform way of determining this would be to use C++ to set up an exception recovery facility and try accessing every byte until one of them suddenly crashes, then use that for the approximate RDRAM limit in megabytes.

In angrylion's plugin source you can find a WIN32-specific way of doing this to calculate the limits.

> I think introducing new RDRAM macros would be better than dividing by 4

Technically it's undefined behavior to be casting pointers for aliasing in this manner anyway.

It would be best if ziggy had never created that `(uint32_t *)gfx_info.RDRAM` #define to begin with and learned to simply iterate over each uint8_t in a rigid and well-defined fashion, which undoubtedly would get optimized to the same thing.

**Comment by purplemarshmallow** [comment]
ok thanks
I used 8 MB as RDRAM size. Not 100% correct but better than letting it crash.

`#define RREADIDX16(in) ((rdp_range_check((in) << 1)) ? 0 : (((UINT16*)m_rdram)[(in) ^ WORD_ADDR_XOR]))`

MAME has this maco looks like this is needed in this case. But z64gl works differntly, it would need some changes to use this macro.

**Comment by purplemarshmallow** [comment]
My fix is not very accurate, the address should change inside the loop
I'll leave it open until it's fixed properly

**Comment by cxd4** [comment]
A nice thing on GitHub is that you can do a search like this:
https://github.com/mamedev/mame/search?utf8=%E2%9C%93&q=rdp_range_check

Their function actually looks wrong there anyway as the address should be &= 0x00FFFFFF but w/e.

**Comment by purplemarshmallow** [comment]
Can I hear your opinion on this?
https://github.com/purplemarshmallow/z64/commit/1aff8d9ffb41756e44a49b30b91772fbd99908f8

**Comment by cxd4** [comment]
Other than what I posted there in comments it seems to be identical to the previous form.

The only other difference I can think of is if the base addresses are not 32-bit aligned.  Like before that commit it was more like (uint32_t *)ptr[i / 4] which forced i to be 32-bit aligned kind of.  Now it divides addresses less, so maybe check values to see if their & 3 (or maybe `& 7` in the case of that 64-bit thing with the dstindex[] usage) are all 0 bits.

**Comment by purplemarshmallow** [comment]
The difference is that in the old version the check 
if (address > 0x007FFFFF)
only checks the base address

The new check 
if (srcindex > 0x007FFFFF)
Should fix that

**Comment by cxd4** [comment]
I meant to comment on that as well, but that's something I subconsciously omitted because that's an improvement I'm quite sure.  The original thing I said about `if (address > MAX_DRAM_ADDRESS)` was a hasty explanation on my part; it is correct that you're checking the cumulative address + i being looped in the current iteration of the loop, instead of only the base address like I originally suggested.

But as far as questionable differences, only what I commented on is different, for better or worse.

**Comment by purplemarshmallow** [comment]
> The only other difference I can think of is if the base addresses are not 32-bit aligned. Like before that commit it was more like (uint32_t *)ptr[i / 4] which forced i to be 32-bit aligned kind of. Now it divides addresses less, so maybe check values to see if their & 3 (or maybe & 7 in the case of that 64-bit thing with the dstindex[] usage) are all 0 bits.

dststart and srcstart &3 are 0. I think it's ok

**Comment by purplemarshmallow** [comment]
Edit: I made a mistake. The branch with mame's tmem code is completely broken and Glover crashes. So I can close this
