### ISSUE TITLE
Rendering in native ingame res.

### ISSUE THREAD

**Issue by ghost** [purplemarshmallow/z64#22]
Just was wondering if it would be possible to allow for rendering at a ingame res or at a low enough res that covers all possible n64 resolutions, and then using a high quality GPU based rescaler (such as NEDI or jinc) to rescale the image back up to native window resolution.

Might help with performance when implementing programmable blending or N64 depth mode emulation on the GPU.

**Comment by cxd4** [comment]
It renders to that already, if you change:
https://github.com/purplemarshmallow/z64/blob/d3f152c15d3ae3ea8b84cce823324bec2f1ac35e/z64gl.conf#L37-L40

**Comment by ghost** [comment]
Oh my bad, ignore the request then. Was just pondering on something I might end up doing too. Didn't know it was already there.

**Comment by AmbientMalice** [comment]
GLideN64 has native resolution rendering now, too. So you may want to take a look there for reference, @mudlord Granted, it needs a bit of work since it won't downsample, and there are some minor bugs here and there. But it massively reduces texture tiling bugs and also arguably improves the image quality of games with 2D elements.

edit:
I dunno how GLideN64 is upscaling its native resolution images, but I think it's doing something cheap and nasty.

**Comment by purplemarshmallow** [comment]
> Might help with performance when implementing programmable blending

RGL_EXACT_BLEND in z64gl is very interesting, I haven't quite figured out how it works. Is it programmable blending? It can handle Vigilante8's special blend modes without special code

**Comment by ghost** [comment]
It simulates the N64's blend modes. Its not programmable blending though,since IIRC it still uses glBlendFuncSeperate.

Ideally you could use GL4 and use coherant image2D access to do all combiner modes as integers. But then there is the problem of something like texture_barrier if you want true programmable blending. I heard PCSX2 has true programmable blends though.

There is one workaround though, and that is extra FBOs to ping-pong between textures to sample/change them though.

**Comment by LegendOfDragoon** [comment]
@purplemarshmallow you tested vigilante 8 with RGL_EXACT_BLEND? If so, how much more accurate is it?

**Comment by purplemarshmallow** [comment]
> It simulates the N64's blend modes. Its not programmable blending though,since IIRC it still uses glBlendFuncSeperate.

I'm not sure but I think it does not use it. This code is disabled if RGL_EXACT_BLEND is defined
https://github.com/purplemarshmallow/z64/blob/master/src/rgl_rendermode.cpp#L713

> @purplemarshmallow you tested vigilante 8 with RGL_EXACT_BLEND? If so, how much more accurate is it?

It fixes the explosions and also problems when looking into light sources

**Comment by ghost** [comment]
Oh my bad, you are right, it completely ignores that code. I wonder how much a performance hit it is keeping exact blends in and killing the rest.

I see how its done now, it implements the N64's combiner formula. There is one other plugin that does things like this: http://www.emutalk.net/threads/56031-mupen64plus-video-videocore-a-WIP-optimized-mobile-graphics-plugin

**Comment by AmbientMalice** [comment]
![92c85b38a1453f8657c2d6cc137d17a6](https://cloud.githubusercontent.com/assets/10704701/13867307/68651760-ed09-11e5-8d2f-460b8ebd2e45.jpg)

I know this is z64gl's topic, and therefore I'm slightly off topic, but it would be great if we could have a new shader-based blending system that could be shared among plugins. The existing, buggy combiners are mostly cut and pasted among plugins, so far as I can tell. PCSX2 gained huge accuracy improvements from its new blending system. It'd be lovely if N64 emulators could have the same thing. I know it's not a trivial task, but still... It'd be a huge benefit.

**Comment by ghost** [comment]
I'm pondering getting out of retirement so I might have time to play around with emulation things again since the drama is now nonexistant. 

A new common ubershader which supports the N64 combiner pipeline would be great indeed. Using angrylion's docs/code as a guide, it might be possible then to accurately do a integer-based combiner shader.

**Comment by purplemarshmallow** [comment]
> Oh my bad, you are right, it completely ignores that code. I wonder how much a performance hit it is keeping exact blends in and killing the rest.

RGL_EXACT_BLEND is marked as highly experimental and slow. Considering that it works very well most games still run fullspeed on my PC.

> The existing, buggy combiners are mostly cut and pasted among plugins

Glide64's combiner uses a lookup table with many lines of code specifically designed for the glide API. z64gl, Rice Video and GLideN64 use shaders but they all look different. GLideN64's combiner is the most accurate

**Comment by purplemarshmallow** [comment]
I would say the plugin with the best blending emulation is z64gl
Even if RGL_EXACT_BLEND is disabled it often still works better than other plugins and has no game specific code

**Comment by LegendOfDragoon** [comment]
> Considering that it works very well most games still run fullspeed on my PC.

What games have you tested with this? I got poor performance in SD Hiryuu, SSB, Tower & Shaft, and V8 2nd offense, all 4 were worse than Angrylion's, on my end. But SM64 was full speed lol.

I still think it was neat to see V8 2nd offense with more accurate graphics on a HW renderer.

**Comment by purplemarshmallow** [comment]
In V8 2nd I get average 45 VI/s with exact blender. Not fullspeed but much faster than angrylion's

**Comment by LegendOfDragoon** [comment]
Man, I really wish I could figure out why z64gl performs poorly on my end! I feel that I should be able to at least get good performance in Tower & Shaft because it hardly uses the RSP. z64 software plugin actually gives good performance for Tower & Shaft.

Out of curiosity, what counter factor are you using for V8 2nd? On CF 2, I get around 42 VI/s using LLE gfx with No Video. How are you even getting 45 VI/s?

Edit: Wow lol, it turns out the reason I was getting terrible performance with No Video, was because of something unrelated. After restarting computer, I was able to get 60. If you're running on CF 1, then 45 VI/s is impressive tbh. Due to the amount of room for improvement in performance for that game.

**Comment by purplemarshmallow** [comment]
I'm using default settings, CF1

angrylion's plugin is really slow for me. With DAC filters disabled I still get only 15 VI/s

**Comment by AmbientMalice** [comment]
@purplemarshmallow Turn on the MAX_RESOLUTION cheat, and then turn on Ultra Resolution ingame, and watch the framerate crash into the floor. (640x480i output.)

**Comment by purplemarshmallow** [comment]
hi-res mode is slow enough for me it gives me 7 VI/s with angrylion's plugin
z64gl's performance should not depend on that but you can still see a difference with lowres=1 enabled in the conf file

**Comment by LegendOfDragoon** [comment]
> I'm using default settings, CF1

Wow in your case, z64gl might not even be the bottleneck. How strong is your cpu?

**Comment by purplemarshmallow** [comment]
intel core i5-2450M
make sure you are using a recent verson of z64gl old versions are very slow in this game

**Comment by LegendOfDragoon** [comment]
> intel core i5-2450M

I guess z64gl is fast for you, even with rgl_exact_blend.

> make sure you are using a recent verson of z64gl old versions are very slow in this game

Ya, I tried a recent build, without rgl_exact_blend, it's only a little faster than Angrylions (w/o filters) for me. When I profiled the game, it said most of the time was spent in glBegin. I wish I knew what's causing the bad performance.
