### ISSUE TITLE
Vigilante8 / F-Zero X texture garbage

### ISSUE THREAD

**Issue by purplemarshmallow** [purplemarshmallow/z64#23]
These games used to run very slow with z64gl and gfx were broken.
I made a half-fix, the slowdown is fixed and gfx look better but still not correct
https://github.com/purplemarshmallow/z64/commit/65cf2036b6e13f7ccc4c04688a849c6641e5f395

The probem is in the load_block command
![2](https://cloud.githubusercontent.com/assets/7283660/13872135/604ccdc8-ece8-11e5-8f0b-ca4ebdef8da5.jpg)
![1](https://cloud.githubusercontent.com/assets/7283660/13872137/61755576-ece8-11e5-947a-8a9543f341f9.jpg)

**Comment by LegendOfDragoon** [comment]
Maybe you can look at GLideN64's code for this issue?

**Comment by purplemarshmallow** [comment]
fixed

**Comment by LegendOfDragoon** [comment]
Is the performance also better?

**Comment by purplemarshmallow** [comment]
This commit fixed performance issues in Vigilante8 / F-Zero X a while ago: https://github.com/purplemarshmallow/z64/commit/65cf2036b6e13f7ccc4c04688a849c6641e5f395
Now the texture garbage is also fixed but I haven't noticed a difference in performance
