### ISSUE TITLE
Zelda Majora's Mask instant crash at midnight of the Final Day

### ISSUE THREAD

**Issue by cxd4** [purplemarshmallow/z64#27]
At least from a brand new file, Mupen64 0.5 instantly segfaults without any error messages to the console at the stroke of 12 at the Night of the Final Day, at the instant in which the cutscene for the Clock Tower unwinding and opening the door to the top should normally begin to play.

Works fine in angrylion LLE.

I will look at debugging this issue myself, but in case anyone else is interested, here is the Mupen64 0.5 saved state I used to double-check that this happens more than just one random time (not sure whether or not it will load on Mupen64 for Windows):
https://dl.dropboxusercontent.com/u/16494013/n64/drdram/Legend%20of%20Zelda%2C%20The%20-%20Majora's%20Mask%20(U)%20%5B!%5D.st0

**Comment by purplemarshmallow** [comment]
On Windows it crashes instantly after the N64 logo with Mupen64 0.5. That does not happen with PJ64

But the angrylion-integration branch seems to work with Mupen

**Comment by cxd4** [comment]
Odd.  Well the GC version releases have no N64 logo, so I wonder if trying those bypasses that.

Maybe it's related to how the GLSL is being compiled/ran differently on both platforms.

Also, I fixed the Dropbox link to point to a file name that actually shows what ROM version the state is for.  Anyway sometime today I mean to start debugging this; I've been both pretty lazy but also busy.

**Comment by purplemarshmallow** [comment]
I can't reprobuce it anymore now it does not crash. I can load the savestate and watch the cutscene without problems

Strange nothing changed, I tested the same git revision

**Comment by purplemarshmallow** [comment]
I figured it out kind of a dumb mistake
I had fb_info enabled without knowing and it crashed the emulator

I can't reproduce your crash at midnight of the Final Day on windows

**Comment by cxd4** [comment]
I'll examine it myself then.  If I remember, the other time it crashed unexpectedly on me was after defeating the Twinmold boss and talking to Sakon right when he tries to steal my sword.

Console output between process_rdp_list() highlights in particular:

```
cmd = 38 (command word = E600000000000000)
done
[...]
cmd = 51 (command word = F30000000702B800)
Signal number 11 caught:
        errno = 0 (Success)
```

It segfaults before the completion of RDP command = 0x33 which is `rdp_load_block`.  Well time to look at that some more I guess. :P

**Comment by cxd4** [comment]
It's crashing here:
https://github.com/purplemarshmallow/z64/blob/master/src/rdp.cpp#L484-L487

**Comment by cxd4** [comment]
I revised load_block() slightly for debugging.

More results:

```
src_base = 0x15CC80
.
src_base = 0x15CC82
.
src_base = 0x15CC84
.
src_base = 0x15CC86
.
src_base = 0x15CC88
.
src_base = 0x15CC8A
.
src_base = 0x15CC8C
.
src_base = 0x15CC8E
.
src_base = 0x15CC90
.
src_base = 0x15CC92
.
src_base = 0x15CC94
.
src_base = 0x15CC96
.
src_base = 0x26C000
Signal number 11 caught:
        errno = 0 (Success)
```

This looks like another memory leak indeed.

Because `src = (uint32_t*)&rdram[0];`, the max limit of `src_base` should be MAX_RDRAM_ADDRESS / sizeof(uint32_t), or `0x007FFFFF >> 2` in the standard 8 MB RDRAM case that Mupen64 always uses.

**Comment by purplemarshmallow** [comment]
Maybe load_tile can also be dangerous

**Comment by cxd4** [comment]
We will see.  For now I have not had any more crashes with this particular game.
