### ISSUE TITLE
Zelda OOT linker optimizations break the ground texture

### ISSUE THREAD

**Issue by purplemarshmallow** [purplemarshmallow/z64#28]
happens randomly and only if linker optimizations are enabled. So I'm wondering if there are more memory issues.
![1](https://cloud.githubusercontent.com/assets/7283660/13899189/caee4904-ede7-11e5-9796-31f676e33de0.jpg)

**Comment by LegendOfDragoon** [comment]
has this been resolved?

**Comment by purplemarshmallow** [comment]
no, still happening if linker optimizations in Visual Studio are enabled

**Comment by purplemarshmallow** [comment]
all memory issues should be fixed now https://github.com/purplemarshmallow/z64/commit/21b41fb1b9d3c46871889da7e741740a3931a917
