### ISSUE TITLE
fb_info option doesn't work in ini

### ISSUE THREAD

**Issue by LegendOfDragoon** [purplemarshmallow/z64#40]
Setting it to 1, doesn't allow me to enable fb reading.

**Comment by purplemarshmallow** [comment]
Yes I broke it...

**Comment by purplemarshmallow** [comment]
Does it work now? Sometimes it does not seem to read the config correctly

**Comment by LegendOfDragoon** [comment]
The regression is now gone. Thanks. There still appears to be a scaling issue though, but maybe due to not using the correct resolution.

Edit: actually just tried 640 x 480 and there's still an issue. 
here's what it looks like in Mario Kart
![image](https://cloud.githubusercontent.com/assets/10492645/21657960/74b78100-d279-11e6-9a91-524a518c6162.png)

I went back and tested original z64gl and it also has the scaling problem, so I guess I'll close the issue.

**Comment by purplemarshmallow** [comment]
I can't reproduce the scaling issue. I tested (E) and (U) versions. Maybe another driver specific bug

**Comment by LegendOfDragoon** [comment]
The odd thing is that I do not recall this issue happening when I tested Mario Kart in the past. Also when using Mesa3D, the issue still exists. Maybe I'll try downloading default config.

Edit: As I suspected, it was a config issue. I recently tried changing options. setting no_npot_fbos to 1, causes the issue.

**Comment by cxd4** [comment]
That's a hack, though.

no_npot_fbos was only added because of crash reports some people had with NVIDIA cards.

NPOT means non-power-of-two support, so FBEs and textures don't need to be 32x32 64x64 etc.

**Comment by purplemarshmallow** [comment]
I don't think this is needed anymore. Every GPU should have non-power-of-two support these days. The ini says it's needed for the geforce 5900 for example. That's over 10 years old hardware...

**Comment by cxd4** [comment]
I'm sure even the 5900 had NPOT support.

It must have just had some conditional bug with using it in conjunction with one of its other features in the Windows releases of its drivers, so ziggy put the feature in.  If it obfuscates the code too much, go ahead and remove it I guess.  I haven't looked for it, so I don't know.

**Comment by LegendOfDragoon** [comment]
I thought maybe I'd benefit from turning it on. For some reason I needed to use POT sized textures for Rice's D3D plugin, in order to get rid of stack hash errors.

When I googled POT textures, people recommended doing that for performance and hardware support. Personally I'd rather not use POT, since that costs more VRAM i think. I guess you can remove the code if you want. I wouldn't mind.

**Comment by purplemarshmallow** [comment]
It's only a few lines
If it may have better performance I'll keep it for benchmarking

**Comment by cxd4** [comment]
I doubt it.  POT dimensions don't increase performance any more often than they increase compatibility if your driver is like 15 years old.

There were maybe two reasons why I ported angrylion's plugin to use POT dimensions in the OpenGL port, and neither of them apply to z64gl.  If you go to the compatibility tab of Project64.exe or whatever and check "Run in 256 colors" then you'll find a driver that requires everything to be power-of-two. :)
