### ISSUE TITLE
kbproto "package not found" warning

### ISSUE THREAD

**Issue by cxd4** [purplemarshmallow/z64#51]
The only warning message left now when doing `make` on this plugin on Linux is
```
Package kbproto was not found in the pkg-config search path.
Perhaps you should add the directory containing `kbproto.pc'
to the PKG_CONFIG_PATH environment variable
Package 'kbproto', required by 'x11', not found
```
I always just ignored it, and never tried to fix it, since the plugin has always just worked all the same.

Since it's the only remaining message though I think I might look at what is causing that once I patch a few warning fixes for the C++ code first.

**Comment by cxd4** [comment]
It looks like it's a dependency of GTK.

If I remove from:
```GTK_FLAGS = `pkg-config gtk+-2.0 --cflags` -D_GTK2```
... down to just ...
```GTK_FLAGS = -D_GTK2```

Then that warning doesn't pop up.  Also, I don't think GTK code is even being used by z64gl, so it must be for some debug stuff ziggy wrote.  I am looking at whether to patch in the kbproto dependency or just remove the GTK configuration from the build process altogether since it's not used by public releases of the plugin.

**Comment by purplemarshmallow** [comment]
I don't see where GTK is used. The debugger just needs SDL for keyboard input and FTGL for font rendering

**Comment by cxd4** [comment]
Well I would like to know why ziggy had the GTK dependency added to the make.

I think nobody would know, though, since I don't find it anywhere either.  I'll probably just PR it out in a few minutes.

**Comment by cxd4** [comment]
I see an old dependency of it from z64gl r12; that shouldn't be of any concern.  A PR can remove it.
