### ISSUE TITLE
possible memory issue in rgl_rendermode?

### ISSUE THREAD

**Issue by purplemarshmallow** [purplemarshmallow/z64#61]
https://github.com/purplemarshmallow/z64/blob/master/src/rgl_rendermode.cpp#L309 
```  
const char * write;
 if ((...)
    write = "gl_FragDepth = c[0];";
```

write is a pointer and there is no malloc anywhere. Isn't this a serious problem, or do I miss something?

**Comment by purplemarshmallow** [comment]
I mixed up something
sprintf(write, "gl_FragDepth = c[0];"); would be problematic

**Comment by cxd4** [comment]
Just more voodoo that C++ allows with strings.

In C the closest thing to that would probably be to use an initializer:
```c
const char * write = "gl_FragDepth = c[0];";
if ((format & RGL_COMB_FMT) != RGL_COMB_FMT_DEPTH)
    write = NULL;
```
